version: '3.1'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker
            POSTGRES_DB: findyourpet
        ports:
            - 5432:5432
